name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  linting_and_testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: dependencies installations 
        run: npm install  
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build step
        run: npm run tsc && cat build/index.js
